#!/bin/bash
echo ">> Cleaning ./dist..."
rm -f dist/wsc.*
echo ">> Combining javascript files..."
cat src/events.js src/templates.js src/lib.js src/packet.js src/channel.js src/tablumps.js src/protocol.js src/commands.js src/client.js src/control.js src/wsc.js > dist/wsc.js
echo ">> Combining CSS files..."
cat css/*.css > dist/wsc.css
echo ">> Compressing javascript source..."
java -jar /usr/local/bin/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar -o dist/wsc.min.js dist/wsc.js
echo ">> Compressing CSS source..."
java -jar /usr/local/bin/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar -o dist/wsc.min.css dist/wsc.css
echo ">> Compressing experimental CSS..."
java -jar /usr/local/bin/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar -o dist/twsc.min.css dist/twsc.css
echo ">> Done!"