#!/usr/bin/python
import re
import os
import sys
import os.path
import argparse

parser = argparse.ArgumentParser(description='Display line counts for a source file.')
parser.add_argument('file', help='source file to get line count for')
args = parser.parse_args()

base = os.path.basename(args.file)
dir = os.path.dirname(args.file)
file = open(os.path.abspath(os.path.join(dir, base)), 'r')
data = file.read().split('\n');

if not '.css' in base:
    file.close()
    file = open(os.path.abspath(os.path.join(dir, 'nom.' + base)), 'r')
    nd = file.read().split('\n')
else:
    nd = []

dispb = base
sys.stdout.write('>>   ' + dispb.ljust(17) + ' | ')
sys.stdout.write(str(len(data)).rjust(5) + ' | '+str(len(nd)).rjust(5)+'\n')
sys.stdout.flush()

